"""
This module provides utility functions for interacting with the SQLite database used in the RAG application.
It includes functions to create necessary tables, manage chat logs, and handle document records.
"""

import sqlite3
from datetime import datetime
import uuid

DB_NAME = "rag_app.db"

# Database Connection
# -------------------
# Establishes a connection to the SQLite database and sets the row factory to enable name-based column access.
def get_db_connection():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return conn

# Database Table Creation
# ----------------------
# Creates the necessary tables used by the application if they don't already exist.

def create_application_logs():
    """
    Create the application_logs table to store chat session logs.
    Fields:
      - id: Primary key
      - session_id: ID representing the chat session
      - user_query: User's input text
      - gpt_response: GPT generated response
      - model: Model used for the response
      - created_at: Timestamp of the log entry
    """
    conn = get_db_connection()
    conn.execute('''CREATE TABLE IF NOT EXISTS application_logs
    (id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT,
    user_query TEXT,
    gpt_response TEXT,
    model TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')
    conn.close()


def create_document_store():
    """
    Create the document_store table to store metadata about uploaded documents.
    Fields:
      - id: Primary key
      - filename: Name of the uploaded file
      - upload_timestamp: When the file was uploaded
    """
    conn = get_db_connection()
    conn.execute('''CREATE TABLE IF NOT EXISTS document_store
                    (id INTEGER PRIMARY KEY AUTOINCREMENT,
                     filename TEXT,
                     upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')
    conn.close()


# Chat Log Management
# -------------------

def insert_application_logs(session_id, user_query, gpt_response, model):
    """
    Insert a new log entry into the application_logs table.

    Parameters:
    - session_id: Identifier for the chat session
    - user_query: The input text sent by the user
    - gpt_response: The response generated by GPT
    - model: Model identifier used for generating the response
    """
    conn = get_db_connection()
    conn.execute('INSERT INTO application_logs (session_id, user_query, gpt_response, model) VALUES (?, ?, ?, ?)'
                 , (session_id, user_query, gpt_response, model))
    conn.commit()
    conn.close()


def get_chat_history(session_id):
    """
    Retrieve chat history for a specified session.

    Parameters:
    - session_id: Identifier for the chat session

    Returns:
    A list of message dictionaries formatted as {"role": ..., "content": ...} appropriate for chat-like UI.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT user_query, gpt_response FROM application_logs WHERE session_id = ? ORDER BY created_at', (session_id,))
    messages = []
    for row in cursor.fetchall():
        messages.extend([
            {"role": "human", "content": row['user_query']},
            {"role": "ai", "content": row['gpt_response']}
        ])
    conn.close()
    return messages


# Document Record Management
# --------------------------

def insert_document_record(filename):
    """
    Insert a new document record in document_store.

    Parameters:
    - filename: Name of the file uploaded

    Returns:
    The database ID of the newly inserted record.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('INSERT INTO document_store (filename) VALUES (?)', (filename,))
    file_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return file_id


def delete_document_record(file_name):
    """
    Delete a document record from document_store by filename.

    Parameters:
    - file_name: Name of the file to delete

    Returns:
    True if the operation was successful.
    """
    conn = get_db_connection()
    conn.execute('DELETE FROM document_store WHERE filename = ?', (file_name,))
    conn.commit()
    conn.close()
    return True


def get_all_documents():
    """
    Retrieve all document records ordered by upload timestamp descending.

    Returns:
    A list of dictionaries with document metadata.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT id, filename, upload_timestamp FROM document_store ORDER BY upload_timestamp DESC')
    documents = cursor.fetchall()
    conn.close()
    return [dict(doc) for doc in documents]


def get_document_details(file_id):
    """
    Retrieve details for a document by its ID.

    Parameters:
    - file_id: The ID of the document

    Returns:
    A list containing a dictionary with the document details.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute(f"SELECT id, filename, upload_timestamp FROM document_store WHERE id = {file_id} ORDER BY upload_timestamp DESC")
    documents = cursor.fetchall()
    conn.close()
    return [dict(doc) for doc in documents]


# Initialize the database tables
create_application_logs()
create_document_store()