from pydantic import BaseModel, Field
from enum import Enum
from datetime import datetime


# ===================== ENUMS =====================
# Enum representing supported model names
class ModelName(str, Enum):
    # ── API Models ──────────────────────────────
    GPT3_5 = "gpt-3.5-turbo"
    GPT4_O = "gpt-4o"
    GPT4_O_MINI = "gpt-4o-mini"
    # ── Local Models (via Ollama) ────────────────
    GEMMA_2B    = "gemma:2b-instruct"    # local chat model


class EmbeddingModel(str, Enum):
    # ── API Embedding ────────────────────────────
    OPENAI      = "openai"                  # text-embedding-ada-002

    # ── Local Embedding (via Ollama) ─────────────
    NOMIC       = "nomic-embed-text"        # local embedding model


# Helper sets used by langchain_utils and chroma_utils to route correctly
OLLAMA_CHAT_MODELS      = {ModelName.GEMMA_2B}
OLLAMA_EMBEDDING_MODELS = {EmbeddingModel.NOMIC}


# ===================== Pydantic Model: Query Input =====================
# This model represents the input payload for a query request to the AI system.
# It includes the question to be asked, an optional session identifier for
# tracking conversation context, and the AI model to be used for processing.
class QueryInput(BaseModel):
    question:        str        = Field(...)
    session_id:      str        = Field(default=None)
    model:           ModelName  = Field(default=ModelName.GPT3_5)
    # embedding_model is kept in session but not sent to /chat;
    # it is sent separately to /upload-doc
    embedding_model: EmbeddingModel = Field(default=EmbeddingModel.OPENAI)


# ===================== Pydantic Model: Query Response =====================
# This model represents the output response after processing a query.
# It includes the answer text generated by the AI, the session identifier
# to maintain context, and the model used to generate the answer.
class QueryResponse(BaseModel):
    answer: str  # Answer text generated by the model
    session_id: str  # Session identifier echoed back from the input
    model: ModelName  # Model used for generating the answer


# ===================== Pydantic Model: Document Information =====================
# This model holds metadata information about an uploaded document/file.
# It includes the document ID, filename, and timestamp of when the document was uploaded.
class DocumentInfo(BaseModel):
    id: int  # Unique document identifier
    filename: str  # Name of the uploaded file
    upload_timestamp: datetime  # Timestamp when the file was uploaded
    #file_size: int  # Optional file size (commented out)
    #content_type: str  # Optional content type (commented out)


# ===================== Pydantic Model: Delete File Request =====================
# This model represents a request to delete a specified file by name.
class DeleteFileRequest(BaseModel):
    file_name: str  # Name of the file to delete